"$schema" = 'https://starship.rs/config-schema.json'

[battery]
format = '\[[$symbol$percentage]($style)\]'

[c]
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[container]
format = '\[[$symbol \[$name\]]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_commit]
format = '\[[\($hash$tag\)]($style)\]'

[git_metrics]
format = '\[[+$added]($added_style)\]\[[-$deleted]($deleted_style)\]'

[git_state]
format = '\[[$state ($progress_current/$progress_total)]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'

[hostname]
format = '\[[$ssh_symbol($hostname)]($style)\] '

[jobs]
format = '\[[$symbol$number]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[shell]
format = '\[[$indicator]($style)\]'

[time]
format = '\[[$time]($style)\]'

[typst]
format = '\[[$symbol($version)]($style)\]'

[username]
format = '\[[$user]($style)\]'
